@extends("template")

@section('content')
<p>
    The operation of websites on the Internet is supported by specific addresses known as top-level domains (TLDs). Within this category, country code Top Level Domains (ccTLDs), or country code top level domains, are particularly relevant as they are linked to specific countries or regions, such as .es for Spain or .eu for the European Union. These ccTLDs are therefore also referred to as geographic domains.
</p>
<p>
    The main administration of all ccTLDs lies with ICANN (Internet Corporation for Assigned Names and Numbers), an entity responsible for the global coordination of the assignment of unique identifiers on the Internet. However, the specific management and registration of these domains is the responsibility of the NICs (Network Information Centers, also known as Domain Name Registries) in each country. For example, in Spain, Red.es plays this role, while in Mexico it is Registry .MX.
</p>
<p>
    Currently, the number of ccTLDs exceeds 200, demonstrating the diversity and global reach of this system. Below is a complete list of all these top-level domains, along with some of their salient features, allowing for a broader and more detailed understanding of their operation and relevance in the Internet landscape.
</p>
<table>
    <tbody>
        <tr>
            <td>
                <p><strong>ccTLD</strong></p>
            </td>
            <td>
                <p><strong>País o Región</strong></p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ac</p>
            </td>
            <td>
                <p>&nbsp;Isla Ascension</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ad</p>
            </td>
            <td>
                <p>&nbsp;Andorra</p>
            </td>
        </tr>
        <tr>
            <td>
                <p><a href="https://www.ionos.es/dominios/ae-dominio" target="_top" title="Registrar tu dominio .ae con IONOS" class="link-internal">.ae</a></p>
            </td>
            <td>
                <p>&nbsp;Emiratos Árabes Unidos</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.af</p>
            </td>
            <td>
                <p>&nbsp;Afganistán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ag</p>
            </td>
            <td>
                <p>&nbsp;Antigua y Barbuda</p>
            </td>
        </tr>
        <tr>
            <td>
                <p><a href="https://www.ionos.es/dominios/ai-dominio" target="_top" title="Registrar tu dominio .ai con IONOS" class="link-internal">.ai</a></p>
            </td>
            <td>
                <p>&nbsp;Anguilla</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.al</p>
            </td>
            <td>
                <p>&nbsp;Albania</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.am</p>
            </td>
            <td>
                <p>&nbsp;Armenia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.an</p>
            </td>
            <td>
                <p>&nbsp;Antillas holandesas (Ahora suprimido –debido a que en 2010 se acordó la disolución política del territorio en el Caribe, en 2015 se creó este ccTLD)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ao</p>
            </td>
            <td>
                <p>&nbsp;Angola</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.aq</p>
            </td>
            <td>
                <p>&nbsp;Antátida</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ar</p>
            </td>
            <td>
                <p>&nbsp;Argentina</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.as</p>
            </td>
            <td>
                <p>&nbsp;Samoa Americana</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.at</p>
            </td>
            <td>
                <p>&nbsp;Austria</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.au</p>
            </td>
            <td>
                <p>&nbsp;Australia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.aw</p>
            </td>
            <td>
                <p>&nbsp;Aruba</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ax</p>
            </td>
            <td>
                <p>&nbsp;Åland (todavía <em>.aland.fi</em> hasta marzo de 2015)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.az</p>
            </td>
            <td>
                <p>&nbsp;Azerbaiyán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ba</p>
            </td>
            <td>
                <p>&nbsp;Bosnia-Herzegovina</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bb</p>
            </td>
            <td>
                <p>&nbsp;Barbados</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bd</p>
            </td>
            <td>
                <p>&nbsp;Bangladés</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.be</p>
            </td>
            <td>
                <p>&nbsp;Bélgica</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bf</p>
            </td>
            <td>
                <p>&nbsp;Burkina&nbsp;Faso</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bg</p>
            </td>
            <td>
                <p>&nbsp;Bulgaria</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bh</p>
            </td>
            <td>
                <p>&nbsp;Baréin</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bi</p>
            </td>
            <td>
                <p>&nbsp;Burundi</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bj</p>
            </td>
            <td>
                <p>&nbsp;Benín</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bl</p>
            </td>
            <td>
                <p>&nbsp;Saint-Barthélemy</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bm</p>
            </td>
            <td>
                <p>&nbsp;Bermudas</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bn</p>
            </td>
            <td>
                <p>&nbsp;Brunéi</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bo</p>
            </td>
            <td>
                <p>&nbsp;Boliva</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.br</p>
            </td>
            <td>
                <p>&nbsp;Brasil</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bq</p>
            </td>
            <td>
                <p>&nbsp;Bonaire, &nbsp;Saba, &nbsp;San Eustaquio</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bs</p>
            </td>
            <td>
                <p>&nbsp;Bahamas</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bt</p>
            </td>
            <td>
                <p>&nbsp;Bután</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bv</p>
            </td>
            <td>
                <p>&nbsp;Isla Bouvet (aún no es posible su registro)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bw</p>
            </td>
            <td>
                <p>&nbsp;Botsvana</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.by</p>
            </td>
            <td>
                <p>&nbsp;Bielorrusia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.bz</p>
            </td>
            <td>
                <p>&nbsp;Belice</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ca</p>
            </td>
            <td>
                <p>&nbsp;Canadá</p>
            </td>
        </tr>
        <tr>
            <td>
                <p><a href="https://www.ionos.es/dominios/cc-dominio" target="_top" title="Registrar tu dominio .cc con IONOS" class="link-internal">.cc</a></p>
            </td>
            <td>
                <p>&nbsp;Islas Cocos</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cd</p>
            </td>
            <td>
                <p>&nbsp;República Democrática del Congo</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cf</p>
            </td>
            <td>
                <p>&nbsp;República Centroafricana</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cg</p>
            </td>
            <td>
                <p>&nbsp;República del Congo</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ch</p>
            </td>
            <td>
                <p>&nbsp;Suiza</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ci</p>
            </td>
            <td>
                <p>&nbsp;Costa de Marfil</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ck</p>
            </td>
            <td>
                <p>&nbsp;Islas Cook</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cl</p>
            </td>
            <td>
                <p>&nbsp;Chile</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cm</p>
            </td>
            <td>
                <p>&nbsp;Camerún</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cn</p>
            </td>
            <td>
                <p>&nbsp;República Popular China</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.co</p>
            </td>
            <td>
                <p>&nbsp;Colombia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cr</p>
            </td>
            <td>
                <p>&nbsp;Costa&nbsp;Rica</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cs</p>
            </td>
            <td>
                <p>&nbsp;Checoslovaquia (ahora eliminado)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cu</p>
            </td>
            <td>
                <p>&nbsp;Cuba</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cv</p>
            </td>
            <td>
                <p>&nbsp;Cabo Verde</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cw</p>
            </td>
            <td>
                <p>&nbsp;Curaçao</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cx</p>
            </td>
            <td>
                <p>&nbsp;Isla de Navidad</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cy</p>
            </td>
            <td>
                <p>&nbsp;Chipre</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.cz</p>
            </td>
            <td>
                <p>&nbsp;Chequia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.dd</p>
            </td>
            <td>
                <p>&nbsp;República Democrática Alemana (nunca fue activado)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.de</p>
            </td>
            <td>
                <p>&nbsp;Alemania</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.dj</p>
            </td>
            <td>
                <p>&nbsp;Djibouti</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.dk</p>
            </td>
            <td>
                <p>&nbsp;Dinamarca</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.dm</p>
            </td>
            <td>
                <p>&nbsp;Dominica</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.do</p>
            </td>
            <td>
                <p>&nbsp;República Dominicana</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.dz</p>
            </td>
            <td>
                <p>&nbsp;Algeria</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ec</p>
            </td>
            <td>
                <p>&nbsp;Ecuador</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ee</p>
            </td>
            <td>
                <p>&nbsp;Estonia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.eg</p>
            </td>
            <td>
                <p>&nbsp;Egipto</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.eh</p>
            </td>
            <td>
                <p>&nbsp;Sahara Occidental (no activado debido al conflicto político entre el gobierno del Sahara Occidental y Marruecos)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.er</p>
            </td>
            <td>
                <p>&nbsp;Eritrea</p>
            </td>
        </tr>
        <tr>
            <td>
                <p><a href="https://www.ionos.es/dominios/es-dominio" target="_top" title="Registrar tu dominio .es con IONOS" class="link-internal">.es</a></p>
            </td>
            <td>
                <p>&nbsp;España</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.et</p>
            </td>
            <td>
                <p>&nbsp;Etiopía</p>
            </td>
        </tr>
        <tr>
            <td>
                <p><a href="https://www.ionos.es/dominios/eu-dominio" target="_top" title="Registrar tu dominio .eu con IONOS" class="link-internal">.eu</a></p>
            </td>
            <td>
                <p>&nbsp;Unión Europea</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.fi</p>
            </td>
            <td>
                <p>&nbsp;Finlandia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.fj</p>
            </td>
            <td>
                <p>&nbsp;Fiji</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.fk</p>
            </td>
            <td>
                <p>&nbsp;Islas Malvinas</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.fm</p>
            </td>
            <td>
                <p>&nbsp;Micronesia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.fo</p>
            </td>
            <td>
                <p>&nbsp;Feroe</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.fr</p>
            </td>
            <td>
                <p>&nbsp;Francia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ga</p>
            </td>
            <td>
                <p>&nbsp;Gabun</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gb</p>
            </td>
            <td>
                <p>&nbsp;Reino Unido (ya no está en uso, en su lugar se utiliza .<em>uk</em>)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gd</p>
            </td>
            <td>
                <p>&nbsp;Granada</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ge</p>
            </td>
            <td>
                <p>&nbsp;Georgia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gf</p>
            </td>
            <td>
                <p>&nbsp;Guyana Francesa</p>
            </td>
        </tr>
        <tr>
            <td>
                <p><a href="https://www.ionos.es/dominios/gg-dominio" target="_top" title="Registrar tu dominio .gg con IONOS" class="link-internal">.gg</a></p>
            </td>
            <td>
                <p>&nbsp;Guernsey</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gh</p>
            </td>
            <td>
                <p>&nbsp;Ghana</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gi</p>
            </td>
            <td>
                <p>&nbsp;Gibraltar</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gl</p>
            </td>
            <td>
                <p>&nbsp;Groenlandia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gm</p>
            </td>
            <td>
                <p>&nbsp;Gambia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gn</p>
            </td>
            <td>
                <p>&nbsp;Guinea</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gp</p>
            </td>
            <td>
                <p>&nbsp;Guadalupe</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gq</p>
            </td>
            <td>
                <p>&nbsp;Guinea Ecuatorial</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gr</p>
            </td>
            <td>
                <p>&nbsp;Grecia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gs</p>
            </td>
            <td>
                <p>&nbsp;Georgia del Sur y las Islas Sandwich del Sur</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gt</p>
            </td>
            <td>
                <p>&nbsp;Guatemala</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gu</p>
            </td>
            <td>
                <p>&nbsp;Guam</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gw</p>
            </td>
            <td>
                <p>&nbsp;Guinea-Bissau</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.gy</p>
            </td>
            <td>
                <p>&nbsp;Guayana</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.hk</p>
            </td>
            <td>
                <p>&nbsp;Hong Kong</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.hm</p>
            </td>
            <td>
                <p>&nbsp;Islas Heard y McDonald</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.hn</p>
            </td>
            <td>
                <p>&nbsp;Honduras</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.hr</p>
            </td>
            <td>
                <p>&nbsp;Croacia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ht</p>
            </td>
            <td>
                <p>&nbsp;Haití</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.hu</p>
            </td>
            <td>
                <p>&nbsp;Hungría</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.id</p>
            </td>
            <td>
                <p>&nbsp;Indonesia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ie</p>
            </td>
            <td>
                <p>&nbsp;Irlanda</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.il</p>
            </td>
            <td>
                <p>&nbsp;Israel</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.im</p>
            </td>
            <td>
                <p>&nbsp;Isla&nbsp;de&nbsp;Man</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.in</p>
            </td>
            <td>
                <p>&nbsp;India</p>
            </td>
        </tr>
        <tr>
            <td>
                <p><a href="https://www.ionos.es/dominios/io-dominio" target="_top" title="Registrar tu dominio .io con IONOS" class="link-internal">.io</a></p>
            </td>
            <td>
                <p>Territorio Británico del Océano Índico</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.iq</p>
            </td>
            <td>
                <p>&nbsp;Irak</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ir</p>
            </td>
            <td>
                <p>&nbsp;Irán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.is</p>
            </td>
            <td>
                <p>&nbsp;Islandia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.it</p>
            </td>
            <td>
                <p>&nbsp;Italia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.je</p>
            </td>
            <td>
                <p>&nbsp;Jersey</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.jm</p>
            </td>
            <td>
                <p>&nbsp;Jamaica</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.jo</p>
            </td>
            <td>
                <p>&nbsp;Jordania</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.jp</p>
            </td>
            <td>
                <p>&nbsp;Japón</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ke</p>
            </td>
            <td>
                <p>&nbsp;Kenia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.kg</p>
            </td>
            <td>
                <p>&nbsp;Kirguistán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.kh</p>
            </td>
            <td>
                <p>&nbsp;Camboya</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ki</p>
            </td>
            <td>
                <p>&nbsp;Kiribati</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.km</p>
            </td>
            <td>
                <p>&nbsp;Comoras</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.kn</p>
            </td>
            <td>
                <p>&nbsp;St. Kitts y Nevis</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.kp</p>
            </td>
            <td>
                <p>&nbsp;Corea del Norte</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.kr</p>
            </td>
            <td>
                <p>&nbsp;Corea del Sur</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.kw</p>
            </td>
            <td>
                <p>&nbsp;Kuwait</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ky</p>
            </td>
            <td>
                <p>&nbsp;Islas Caimán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.kz</p>
            </td>
            <td>
                <p>&nbsp;Kazajstán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.la</p>
            </td>
            <td>
                <p>&nbsp;Laos</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.lb</p>
            </td>
            <td>
                <p>&nbsp;Líbano</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.lc</p>
            </td>
            <td>
                <p>&nbsp;Santa&nbsp;Lucia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.li</p>
            </td>
            <td>
                <p>&nbsp;Liechtenstein</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.lk</p>
            </td>
            <td>
                <p>&nbsp;Sri&nbsp;Lanka</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.lr</p>
            </td>
            <td>
                <p>&nbsp;Liberia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ls</p>
            </td>
            <td>
                <p>&nbsp;Lesoto</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.lt</p>
            </td>
            <td>
                <p>&nbsp;Lituania</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.lu</p>
            </td>
            <td>
                <p>&nbsp;Luxemburgo</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.lv</p>
            </td>
            <td>
                <p>&nbsp;Letonia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ly</p>
            </td>
            <td>
                <p>&nbsp;Libia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ma</p>
            </td>
            <td>
                <p>&nbsp;Marruecos</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mc</p>
            </td>
            <td>
                <p>&nbsp;Mónaco</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.md</p>
            </td>
            <td>
                <p>&nbsp;Moldavia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.me</p>
            </td>
            <td>
                <p>&nbsp;Montenegro</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mf</p>
            </td>
            <td>
                <p>&nbsp;Saint-Martin</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mg</p>
            </td>
            <td>
                <p>&nbsp;Madagascar</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mh</p>
            </td>
            <td>
                <p>&nbsp;Islas Marshall</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mk</p>
            </td>
            <td>
                <p>&nbsp;Macedonia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ml</p>
            </td>
            <td>
                <p>&nbsp;Mali</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mm</p>
            </td>
            <td>
                <p>&nbsp;Myanmar</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mn</p>
            </td>
            <td>
                <p>&nbsp;Mongolia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mo</p>
            </td>
            <td>
                <p>&nbsp;Macau</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mp</p>
            </td>
            <td>
                <p>&nbsp;Islas Marinas del Norte</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mq</p>
            </td>
            <td>
                <p>&nbsp;Martinica</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mr</p>
            </td>
            <td>
                <p>&nbsp;Mauritania</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ms</p>
            </td>
            <td>
                <p>&nbsp;Montserrat</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mt</p>
            </td>
            <td>
                <p>&nbsp;Malta</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mu</p>
            </td>
            <td>
                <p>&nbsp;República de Mauricio</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mv</p>
            </td>
            <td>
                <p>&nbsp;Maledivas</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mw</p>
            </td>
            <td>
                <p>&nbsp;Malawi</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mx</p>
            </td>
            <td>
                <p>&nbsp;México</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.my</p>
            </td>
            <td>
                <p>&nbsp;Malasia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.mz</p>
            </td>
            <td>
                <p>&nbsp;Mozambique</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.na</p>
            </td>
            <td>
                <p>&nbsp;Namibia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.nc</p>
            </td>
            <td>
                <p>&nbsp;Caledonia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ne</p>
            </td>
            <td>
                <p>&nbsp;Níger</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.nf</p>
            </td>
            <td>
                <p>&nbsp;Isla Norfolk</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ng</p>
            </td>
            <td>
                <p>&nbsp;Nigeria</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ni</p>
            </td>
            <td>
                <p>&nbsp;Nicaragua</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.nl</p>
            </td>
            <td>
                <p>&nbsp;Países Bajos</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.no</p>
            </td>
            <td>
                <p>&nbsp;Noruega</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.np</p>
            </td>
            <td>
                <p>&nbsp;Nepal</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.nr</p>
            </td>
            <td>
                <p>&nbsp;Nauru</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.nu</p>
            </td>
            <td>
                <p>&nbsp;Niue</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.nz</p>
            </td>
            <td>
                <p>&nbsp;Nueva Zelanda</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.om</p>
            </td>
            <td>
                <p>&nbsp;Omán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.pa</p>
            </td>
            <td>
                <p>&nbsp;Panamá</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.pe</p>
            </td>
            <td>
                <p>&nbsp;Perú</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.pf</p>
            </td>
            <td>
                <p>&nbsp;Polinesia Francesa</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.pg</p>
            </td>
            <td>
                <p>&nbsp;Papua Nueva Guinea</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ph</p>
            </td>
            <td>
                <p>&nbsp;Filipinas</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.pk</p>
            </td>
            <td>
                <p>&nbsp;Pakistán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.pl</p>
            </td>
            <td>
                <p>&nbsp;Polonia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.pm</p>
            </td>
            <td>
                <p>&nbsp;Saint Pedro y Miquelón</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.pn</p>
            </td>
            <td>
                <p>&nbsp;Islas Pitcairn</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.pr</p>
            </td>
            <td>
                <p>&nbsp;Puerto&nbsp;Rico</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ps</p>
            </td>
            <td>
                <p>&nbsp;Estado de Palestina</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.pt</p>
            </td>
            <td>
                <p>&nbsp;Portugal</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.pw</p>
            </td>
            <td>
                <p>&nbsp;Palau</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.py</p>
            </td>
            <td>
                <p>&nbsp;Paraguay</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.qa</p>
            </td>
            <td>
                <p>&nbsp;Katar</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.re</p>
            </td>
            <td>
                <p>&nbsp;Reunión</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ro</p>
            </td>
            <td>
                <p>&nbsp;Rumania</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.rs</p>
            </td>
            <td>
                <p>&nbsp;Serbia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ru</p>
            </td>
            <td>
                <p>&nbsp;Rusia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.rw</p>
            </td>
            <td>
                <p>&nbsp;Ruanda</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sa</p>
            </td>
            <td>
                <p>&nbsp;Arabia Saudita</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sb</p>
            </td>
            <td>
                <p>&nbsp;Islas Salomón</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sc</p>
            </td>
            <td>
                <p>&nbsp;Seychelles</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sd</p>
            </td>
            <td>
                <p>&nbsp;Sudán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.se</p>
            </td>
            <td>
                <p>&nbsp;Suecia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sg</p>
            </td>
            <td>
                <p>&nbsp;Singapur</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sh</p>
            </td>
            <td>
                <p>&nbsp;St. Helena</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.si</p>
            </td>
            <td>
                <p>&nbsp;Eslovenia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sj</p>
            </td>
            <td>
                <p>&nbsp;Svalbard y Jan Mayen (aún no es posible su registro)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sk</p>
            </td>
            <td>
                <p>&nbsp;Eslovaquia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sl</p>
            </td>
            <td>
                <p>&nbsp;Sierra&nbsp;Leona</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sm</p>
            </td>
            <td>
                <p>&nbsp;San&nbsp;Marino</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sn</p>
            </td>
            <td>
                <p>&nbsp;Senegal</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.so</p>
            </td>
            <td>
                <p>&nbsp;Somalia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sr</p>
            </td>
            <td>
                <p>&nbsp;Surinam</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ss</p>
            </td>
            <td>
                <p>&nbsp;Sudán del Sur</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.st</p>
            </td>
            <td>
                <p>&nbsp;Santo Tomé y Príncipe</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.su</p>
            </td>
            <td>
                <p>&nbsp;Unión Soviética (desde la disulución se utiliza el TLD ruso)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sv</p>
            </td>
            <td>
                <p>&nbsp;El&nbsp;Salvador</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sx</p>
            </td>
            <td>
                <p>&nbsp;Sint Maarten</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sy</p>
            </td>
            <td>
                <p>&nbsp;Siria</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.sz</p>
            </td>
            <td>
                <p>&nbsp;Swazilandia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tc</p>
            </td>
            <td>
                <p>&nbsp;Islas Turcas y Caicos</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.td</p>
            </td>
            <td>
                <p>&nbsp;Chad</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tf</p>
            </td>
            <td>
                <p>&nbsp;Tierras Australes y Antárticas Francesas</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tg</p>
            </td>
            <td>
                <p>&nbsp;Togo</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.th</p>
            </td>
            <td>
                <p>&nbsp;Tailandia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tj</p>
            </td>
            <td>
                <p>&nbsp;Tayikistán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tk</p>
            </td>
            <td>
                <p>&nbsp;Tokelau</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tl</p>
            </td>
            <td>
                <p>&nbsp;Timor Occidental (anteriormente<em> .tp</em>)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tm</p>
            </td>
            <td>
                <p>&nbsp;Turkmenistán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tn</p>
            </td>
            <td>
                <p>&nbsp;Túnez</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.to</p>
            </td>
            <td>
                <p>&nbsp;Tonga</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tp</p>
            </td>
            <td>
                <p>&nbsp;Timor Oriental (ahora eliminado – sustituido desde 2002 con <em>.tl</em>)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tr</p>
            </td>
            <td>
                <p>&nbsp;Turquía, &nbsp;República Turca del Norte de Chipre</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tt</p>
            </td>
            <td>
                <p>&nbsp;Trinidad y Tobago</p>
            </td>
        </tr>
        <tr>
            <td>
                <p><a href="https://www.ionos.es/dominios/tv-dominio" target="_top" title="Registrar tu dominio .tv con IONOS" class="link-internal">.tv</a></p>
            </td>
            <td>
                <p>&nbsp;Tuvalu</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tw</p>
            </td>
            <td>
                <p>&nbsp;Taiwán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.tz</p>
            </td>
            <td>
                <p>&nbsp;Tanzania</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ua</p>
            </td>
            <td>
                <p>&nbsp;Ucrania</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ug</p>
            </td>
            <td>
                <p>&nbsp;Uganda</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.uk</p>
            </td>
            <td>
                <p>&nbsp;Reino Unido</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.um</p>
            </td>
            <td>
                <p>&nbsp;Islas Ultramarinas Menores de Estados Unidos (ahora eliminado)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.us</p>
            </td>
            <td>
                <p>&nbsp;Estados Unidos</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.uy</p>
            </td>
            <td>
                <p>&nbsp;Uruguay</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.uz</p>
            </td>
            <td>
                <p>&nbsp;Uzbekistán</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.va</p>
            </td>
            <td>
                <p>&nbsp;Ciudad del Vaticano</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.vc</p>
            </td>
            <td>
                <p>&nbsp;St.&nbsp;Vincente y las Granadinas</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ve</p>
            </td>
            <td>
                <p>&nbsp;Venezuela</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.vg</p>
            </td>
            <td>
                <p>&nbsp;Islas Vírgenes Británicas</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.vi</p>
            </td>
            <td>
                <p>&nbsp;Islas Vírgenes de los EE.UU</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.vn</p>
            </td>
            <td>
                <p>&nbsp;Vietnam</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.vu</p>
            </td>
            <td>
                <p>&nbsp;Vanuatu</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.wf</p>
            </td>
            <td>
                <p>&nbsp;Wallis y Futuna (también<em> .fr</em>)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ws</p>
            </td>
            <td>
                <p>&nbsp;Samoa</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.ye</p>
            </td>
            <td>
                <p>&nbsp;Yemen</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.yt</p>
            </td>
            <td>
                <p>&nbsp;Mayotte (región francesa – también <em>.fr</em>)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.yu</p>
            </td>
            <td>
                <p>&nbsp;Yugoslavia (ahora eliminado – después de la disolución se utilizó, hasta 2010, el TLD de Serbia y Montenegro)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.za</p>
            </td>
            <td>
                <p>&nbsp;Sudáfrica</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.zm</p>
            </td>
            <td>
                <p>&nbsp;Zambia</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.zr</p>
            </td>
            <td>
                <p>&nbsp;Zaire (ahora eliminado, utiliza <em>.cd</em> desde el cambio del nombre del país en 1997)</p>
            </td>
        </tr>
        <tr>
            <td>
                <p>.zw</p>
            </td>
            <td>
                <p>&nbsp;Zimbabue</p>
            </td>
        </tr>
    </tbody>
</table>
<span>Datos obtenidos de <a href="https://www.ionos.es/digitalguide/dominios/extensiones-de-dominio/cctld-la-lista-completa-de-dominios-por-pais/">ionos</a> </span>
@endSection

@section('title', 'List of domain extensions by country.')